replicaCount: 2

image:
  repository: "992382545251.dkr.ecr.us-east-1.amazonaws.com/alon-aviad-repo"
  tag: "status-page-18"

app:
  port: 8000
  name: "status-page"
  siteUrl: "https://statuspage-aa.click/"

database:
  host: "status-page-db-aa.cx248m4we6k7.us-east-1.rds.amazonaws.com"
  port: "5432"
  name: "statuspage"
  user: "dbadmin"

redis:
  host: "status-page-redis-aa.7fftml.0001.use1.cache.amazonaws.com"
  port: "6379"

email:
  server: "smtp.gmail.com"
  port: "465"
  username: "statuspageaa@gmail.com"
  use_ssl: "True"
  use_tls: "False"
  timeout: "60"
  # Note: password should be stored in a secret (AWS Secrets Manager)

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "statuspage-aa.click"
  path: "/"
  healthCheckPath: "/"
  certificateArn: ""  # Set to ACM cert ARN after terraform apply, e.g. from: terraform output acm_certificate_arn

externalSecrets:
  region: us-east-1
  secretStoreName: aws-secretsmanager
  refreshInterval: 1h
  remoteSecretName: "status-page-db-aa-credentials"
  k8sSecretName: "status-page-secret"