apiVersion: v1
kind: ConfigMap
metadata:
  name: status-page-config
data:
  # === PostgreSQL Database ===
  DB_HOST: "status-page-db-aa.cx248m4we6k7.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "statuspage"
  DB_USER: "dbadmin"

  # === Redis Cache ===
  REDIS_HOST: "status-page-redis-aa.7fftml.0001.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"