apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-server
          - argocd-repo-server
          - argocd-metrics
          - argocd-application-controller
  podMetricsEndpoints:
    - port: metrics
      interval: 30s