apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page-web
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
      - name: status-page-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.app.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.ingress.healthCheckPath | default "/" }}
            port: {{ .Values.app.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.ingress.healthCheckPath | default "/" }}
            port: {{ .Values.app.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: status-page-config
        - secretRef:
            name: status-page-secret