apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page-web
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      containers:
      - name: status-page-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.app.port }}
        envFrom:
        - configMapRef:
            name: status-page-config
        - secretRef:
            name: status-page-secret