apiVersion: v1
kind: Service
metadata:
  name: status-page-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: status-page 
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.app.port }} 