apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: status-page-external-secret
spec:
  refreshInterval: 1h 
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: status-page-secret 
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD 
      remoteRef:
        key: "status-page-db-aa-credentials" 
        property: password 